# Redis PersistentVolume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: erechnung
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
