# Generated by Django 5.1.15 on 2026-02-21 12:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Company Name")),
                ("legal_name", models.CharField(blank=True, max_length=255, verbose_name="Legal Name")),
                ("tax_id", models.CharField(max_length=50, unique=True, verbose_name="Tax ID")),
                ("vat_id", models.CharField(blank=True, max_length=50, verbose_name="VAT ID")),
                (
                    "commercial_register",
                    models.CharField(blank=True, max_length=100, verbose_name="Commercial Register"),
                ),
                ("address_line1", models.CharField(max_length=255, verbose_name="Address Line 1")),
                ("address_line2", models.CharField(blank=True, max_length=255, verbose_name="Address Line 2")),
                ("postal_code", models.CharField(max_length=20, verbose_name="Postal Code")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state_province", models.CharField(blank=True, max_length=100, verbose_name="State/Province")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Phone")),
                ("fax", models.CharField(blank=True, max_length=50, verbose_name="Fax")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo for invoices (PNG/JPG, max 60mm × 20mm recommended)",
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, verbose_name="Bank Name")),
                ("bank_account", models.CharField(blank=True, max_length=50, verbose_name="Bank Account")),
                ("iban", models.CharField(blank=True, max_length=34, verbose_name="IBAN")),
                ("bic", models.CharField(blank=True, max_length=11, verbose_name="BIC/SWIFT")),
                ("default_currency", models.CharField(default="EUR", max_length=3, verbose_name="Default Currency")),
                (
                    "default_payment_terms",
                    models.PositiveIntegerField(default=30, verbose_name="Default Payment Terms (days)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 code (e.g., DE, AT, FR)",
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "code_alpha3",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 code (e.g., DEU, AUT, FRA)",
                        max_length=3,
                        verbose_name="Alpha-3 Code",
                    ),
                ),
                (
                    "numeric_code",
                    models.CharField(
                        help_text="ISO 3166-1 numeric code (e.g., 276, 040, 250)",
                        max_length=3,
                        verbose_name="Numeric Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official country name in English", max_length=100, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_local",
                    models.CharField(
                        help_text="Country name in local language", max_length=100, verbose_name="Name (Local)"
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., EUR, CHF, USD)",
                        max_length=3,
                        verbose_name="Currency Code",
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(
                        help_text="Currency name (e.g., Euro, Swiss Franc)",
                        max_length=50,
                        verbose_name="Currency Name",
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        help_text="Currency symbol (e.g., €, CHF, $)", max_length=5, verbose_name="Currency Symbol"
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        help_text="ISO 639-1 language code (e.g., de, en, fr)",
                        max_length=5,
                        verbose_name="Default Language",
                    ),
                ),
                (
                    "is_eu_member",
                    models.BooleanField(
                        default=False,
                        help_text="Is this country a member of the European Union?",
                        verbose_name="EU Member",
                    ),
                ),
                (
                    "is_eurozone",
                    models.BooleanField(
                        default=False,
                        help_text="Does this country use the Euro as official currency?",
                        verbose_name="Eurozone Member",
                    ),
                ),
                (
                    "standard_vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Standard VAT rate in percent (e.g., 19.00 for Germany)",
                        max_digits=5,
                        verbose_name="Standard VAT Rate",
                    ),
                ),
                (
                    "reduced_vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reduced VAT rate in percent (e.g., 7.00 for Germany)",
                        max_digits=5,
                        null=True,
                        verbose_name="Reduced VAT Rate",
                    ),
                ),
                (
                    "super_reduced_vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Super reduced VAT rate (used in FR, ES, IE, etc.)",
                        max_digits=5,
                        null=True,
                        verbose_name="Super Reduced VAT Rate",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="DD.MM.YYYY",
                        help_text="Date format pattern",
                        max_length=20,
                        verbose_name="Date Format",
                    ),
                ),
                (
                    "decimal_separator",
                    models.CharField(
                        default=",",
                        help_text="Decimal separator character",
                        max_length=1,
                        verbose_name="Decimal Separator",
                    ),
                ),
                (
                    "thousands_separator",
                    models.CharField(
                        default=".",
                        help_text="Thousands separator character",
                        max_length=1,
                        verbose_name="Thousands Separator",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessPartner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_customer",
                    models.BooleanField(
                        default=True,
                        help_text="Partner can receive invoices from us (outgoing invoices)",
                        verbose_name="Is Customer",
                    ),
                ),
                (
                    "is_supplier",
                    models.BooleanField(
                        default=False,
                        help_text="Partner can send invoices to us (incoming invoices)",
                        verbose_name="Is Supplier",
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("BUSINESS", "Business"),
                            ("GOVERNMENT", "Government"),
                            ("NON_PROFIT", "Non-Profit"),
                        ],
                        default="BUSINESS",
                        max_length=20,
                        verbose_name="Partner Type",
                    ),
                ),
                (
                    "partner_number",
                    models.CharField(blank=True, max_length=50, unique=True, verbose_name="Partner Number"),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, verbose_name="First Name")),
                ("last_name", models.CharField(blank=True, max_length=100, verbose_name="Last Name")),
                ("company_name", models.CharField(blank=True, max_length=255, verbose_name="Company Name")),
                ("legal_name", models.CharField(blank=True, max_length=255, verbose_name="Legal Name")),
                ("tax_id", models.CharField(blank=True, max_length=50, verbose_name="Tax ID")),
                ("vat_id", models.CharField(blank=True, max_length=50, verbose_name="VAT ID")),
                (
                    "commercial_register",
                    models.CharField(blank=True, max_length=100, verbose_name="Commercial Register"),
                ),
                ("address_line1", models.CharField(max_length=255, verbose_name="Address Line 1")),
                ("address_line2", models.CharField(blank=True, max_length=255, verbose_name="Address Line 2")),
                ("postal_code", models.CharField(max_length=20, verbose_name="Postal Code")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state_province", models.CharField(blank=True, max_length=100, verbose_name="State/Province")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Phone")),
                ("fax", models.CharField(blank=True, max_length=50, verbose_name="Fax")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "payment_terms",
                    models.PositiveIntegerField(blank=True, default=30, verbose_name="Payment Terms (days)"),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Credit Limit"
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(blank=True, default="EUR", max_length=3, verbose_name="Preferred Currency"),
                ),
                (
                    "default_reference_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Default prefix for customer order references (e.g., 'PO-', 'ORDER-', 'PROJ-')",
                        max_length=20,
                        verbose_name="Default Reference Prefix",
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=255, verbose_name="Contact Person")),
                (
                    "accounting_contact",
                    models.CharField(blank=True, max_length=255, verbose_name="Accounting Contact"),
                ),
                ("accounting_email", models.EmailField(blank=True, max_length=254, verbose_name="Accounting Email")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="country",
                        help_text="Partner's country - determines tax rates and currency",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_partners",
                        to="invoice_app.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Partner",
                "verbose_name_plural": "Business Partners",
                "db_table": "invoice_app_businesspartner",
                "ordering": ["company_name", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "invoice_number",
                    models.CharField(
                        default="DEFAULT",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invoice number can only contain letters, numbers, and hyphens.",
                                regex="^[A-Za-z0-9-]+$",
                            )
                        ],
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Invoice"),
                            ("CREDIT_NOTE", "Credit Note"),
                            ("DEBIT_NOTE", "Debit Note"),
                            ("CORRECTED", "Corrected Invoice"),
                            ("PARTIAL", "Partial Invoice"),
                            ("FINAL", "Final Invoice"),
                        ],
                        default="INVOICE",
                        max_length=20,
                        verbose_name="Invoice Type",
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now, verbose_name="Issue Date")),
                ("due_date", models.DateField(default=django.utils.timezone.now, verbose_name="Due Date")),
                ("delivery_date", models.DateField(blank=True, null=True, verbose_name="Delivery Date")),
                ("currency", models.CharField(default="EUR", max_length=3, verbose_name="Currency")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        blank=True,
                        default=30,
                        help_text="Number of days until payment is due (e.g. 30 for 'net 30')",
                        null=True,
                        verbose_name="Payment Terms (days)",
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=100, verbose_name="Payment Method")),
                ("payment_reference", models.CharField(blank=True, max_length=100, verbose_name="Payment Reference")),
                (
                    "buyer_reference",
                    models.CharField(
                        blank=True,
                        help_text="Customer's order or reference number (Ihr Zeichen)",
                        max_length=100,
                        verbose_name="Buyer Reference",
                    ),
                ),
                (
                    "seller_reference",
                    models.CharField(
                        blank=True,
                        help_text="Our internal reference or project number (Unser Zeichen)",
                        max_length=100,
                        verbose_name="Seller Reference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/pdf/", verbose_name="PDF File"),
                ),
                (
                    "xml_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/xml/", verbose_name="XML File"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "business_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_invoices",
                        to="invoice_app.businesspartner",
                        verbose_name="Business Partner",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_invoices",
                        to="invoice_app.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date", "-invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="invoices/attachments/", verbose_name="File")),
                ("description", models.CharField(max_length=255, verbose_name="Description")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="invoice_app.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Attachment",
                "verbose_name_plural": "Invoice Attachments",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(default="Item", max_length=255, verbose_name="Description")),
                ("product_code", models.CharField(blank=True, max_length=100, verbose_name="Product Code")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.IntegerField(
                        choices=[
                            (1, "Stück"),
                            (2, "Stunde"),
                            (3, "Tag"),
                            (4, "Kilogramm"),
                            (5, "Liter"),
                            (6, "Monat"),
                        ],
                        default=1,
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Tax Rate",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Line Subtotal",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Line Total",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Discount %",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "discount_reason",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Discount Reason"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoice_app.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line",
                "verbose_name_plural": "Invoice Lines",
            },
        ),
        migrations.CreateModel(
            name="InvoiceAllowanceCharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_charge",
                    models.BooleanField(
                        default=False,
                        help_text="True = Zuschlag (charge), False = Rabatt (allowance)",
                        verbose_name="Is Charge",
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "calculation_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Optional: percentage on basis_amount that gives actual_amount",
                        max_digits=7,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Calculation %",
                    ),
                ),
                (
                    "basis_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: base for calculation_percent",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Basis Amount",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="UNTDID 5189 (Rabatt) or 7161 (Zuschlag) code, e.g. '95' for discount",
                        max_length=10,
                        verbose_name="Reason Code",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text reason (used if reason_code is empty)",
                        max_length=255,
                        verbose_name="Reason",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Sort Order")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance_charges",
                        to="invoice_app.invoice",
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for line-level allowance/charge (EN16931 SpecifiedLineTradeSettlement). Leave null for header-level (ApplicableHeaderTradeSettlement).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance_charges",
                        to="invoice_app.invoiceline",
                        verbose_name="Invoice Line",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Allowance/Charge",
                "verbose_name_plural": "Invoice Allowances/Charges",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_code", models.CharField(max_length=100, unique=True, verbose_name="Product Code")),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical Product"),
                            ("SERVICE", "Service"),
                            ("DIGITAL", "Digital Product"),
                            ("SUBSCRIPTION", "Subscription"),
                        ],
                        default="PHYSICAL",
                        max_length=20,
                        verbose_name="Product Type",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, verbose_name="Category")),
                ("subcategory", models.CharField(blank=True, max_length=100, verbose_name="Subcategory")),
                ("brand", models.CharField(blank=True, max_length=100, verbose_name="Brand")),
                ("manufacturer", models.CharField(blank=True, max_length=255, verbose_name="Manufacturer")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Base Price",
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3, verbose_name="Currency")),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Cost Price",
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="List Price",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.IntegerField(
                        choices=[
                            (1, "Stück"),
                            (2, "Stunde"),
                            (3, "Tag"),
                            (4, "Kilogramm"),
                            (5, "Liter"),
                            (6, "Monat"),
                        ],
                        default=1,
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Weight in kg",
                        max_digits=10,
                        null=True,
                        verbose_name="Weight",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, help_text="L x W x H in cm", max_length=100, verbose_name="Dimensions"
                    ),
                ),
                (
                    "tax_category",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard Rate"),
                            ("REDUCED", "Reduced Rate"),
                            ("ZERO", "Zero Rate"),
                            ("EXEMPT", "Exempt"),
                            ("REVERSE_CHARGE", "Reverse Charge"),
                        ],
                        default="STANDARD",
                        max_length=20,
                        verbose_name="Tax Category",
                    ),
                ),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.0,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Default Tax Rate",
                    ),
                ),
                ("tax_code", models.CharField(blank=True, max_length=50, verbose_name="Tax Code")),
                ("track_inventory", models.BooleanField(default=False, verbose_name="Track Inventory")),
                (
                    "stock_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True, verbose_name="Stock Quantity"
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True, verbose_name="Minimum Stock"
                    ),
                ),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Barcode")),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500, verbose_name="Tags"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_sellable", models.BooleanField(default=True, verbose_name="Is Sellable")),
                ("discontinuation_date", models.DateField(blank=True, null=True, verbose_name="Discontinuation Date")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["product_code", "name"],
            },
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="invoice_app.product",
                verbose_name="Product",
            ),
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=100, unique=True, verbose_name="Configuration Key")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("SECURITY", "Security"),
                            ("EMAIL", "Email"),
                            ("PDF", "PDF Generation"),
                            ("XML", "XML/ZUGFeRD"),
                            ("INTEGRATION", "Integration"),
                            ("BACKUP", "Backup"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("value", models.TextField(verbose_name="Value")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("FLOAT", "Float"),
                            ("BOOLEAN", "Boolean"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        max_length=10,
                        verbose_name="Value Type",
                    ),
                ),
                ("default_value", models.TextField(blank=True, verbose_name="Default Value")),
                ("name", models.CharField(max_length=200, verbose_name="Display Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("validation_regex", models.CharField(blank=True, max_length=500, verbose_name="Validation Regex")),
                (
                    "choices",
                    models.JSONField(
                        blank=True, default=list, help_text="List of valid choices", verbose_name="Choices"
                    ),
                ),
                ("is_required", models.BooleanField(default=True, verbose_name="Is Required")),
                ("is_sensitive", models.BooleanField(default=False, verbose_name="Is Sensitive")),
                ("is_system", models.BooleanField(default=False, verbose_name="Is System Setting")),
                ("requires_restart", models.BooleanField(default=False, verbose_name="Requires Restart")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Role Name")),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("MANAGER", "Manager"),
                            ("ACCOUNTANT", "Accountant"),
                            ("CLERK", "Clerk"),
                            ("AUDITOR", "Auditor"),
                            ("READ_ONLY", "Read Only"),
                        ],
                        max_length=20,
                        verbose_name="Role Type",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_system_role", models.BooleanField(default=False, verbose_name="Is System Role")),
                ("can_create_invoice", models.BooleanField(default=False, verbose_name="Can Create Invoices")),
                ("can_edit_invoice", models.BooleanField(default=False, verbose_name="Can Edit Invoices")),
                ("can_delete_invoice", models.BooleanField(default=False, verbose_name="Can Delete Invoices")),
                ("can_send_invoice", models.BooleanField(default=False, verbose_name="Can Send Invoices")),
                ("can_mark_paid", models.BooleanField(default=False, verbose_name="Can Mark as Paid")),
                ("can_generate_pdf", models.BooleanField(default=False, verbose_name="Can Generate PDF")),
                ("can_create_customer", models.BooleanField(default=False, verbose_name="Can Create Customers")),
                ("can_edit_customer", models.BooleanField(default=False, verbose_name="Can Edit Customers")),
                ("can_delete_customer", models.BooleanField(default=False, verbose_name="Can Delete Customers")),
                ("can_create_product", models.BooleanField(default=False, verbose_name="Can Create Products")),
                ("can_edit_product", models.BooleanField(default=False, verbose_name="Can Edit Products")),
                ("can_delete_product", models.BooleanField(default=False, verbose_name="Can Delete Products")),
                ("can_manage_inventory", models.BooleanField(default=False, verbose_name="Can Manage Inventory")),
                ("can_edit_company", models.BooleanField(default=False, verbose_name="Can Edit Company")),
                ("can_view_reports", models.BooleanField(default=False, verbose_name="Can View Reports")),
                ("can_export_data", models.BooleanField(default=False, verbose_name="Can Export Data")),
                ("can_view_audit_logs", models.BooleanField(default=False, verbose_name="Can View Audit Logs")),
                ("can_backup_data", models.BooleanField(default=False, verbose_name="Can Backup Data")),
                ("can_manage_users", models.BooleanField(default=False, verbose_name="Can Manage Users")),
                ("can_manage_roles", models.BooleanField(default=False, verbose_name="Can Manage Roles")),
                ("can_change_settings", models.BooleanField(default=False, verbose_name="Can Change Settings")),
                (
                    "max_invoice_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum invoice amount this role can create/approve",
                        max_digits=15,
                        null=True,
                        verbose_name="Max Invoice Amount",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_id", models.CharField(blank=True, max_length=50, verbose_name="Employee ID")),
                ("department", models.CharField(blank=True, max_length=100, verbose_name="Department")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Phone")),
                ("mobile", models.CharField(blank=True, max_length=50, verbose_name="Mobile")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German"), ("fr", "French"), ("es", "Spanish")],
                        default="en",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50, verbose_name="Timezone")),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("%Y-%m-%d", "YYYY-MM-DD"),
                            ("%d.%m.%Y", "DD.MM.YYYY"),
                            ("%m/%d/%Y", "MM/DD/YYYY"),
                            ("%d/%m/%Y", "DD/MM/YYYY"),
                        ],
                        default="%Y-%m-%d",
                        max_length=20,
                        verbose_name="Date Format",
                    ),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="Last Login IP")),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Failed Login Attempts"),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="Account Locked Until"),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Password Changed At"),
                ),
                ("must_change_password", models.BooleanField(default=False, verbose_name="Must Change Password")),
                ("mfa_enabled", models.BooleanField(default=False, verbose_name="MFA Enabled")),
                ("mfa_secret", models.CharField(blank=True, max_length=32, verbose_name="MFA Secret")),
                ("backup_codes", models.JSONField(blank=True, default=list, verbose_name="Backup Codes")),
                (
                    "concurrent_sessions_limit",
                    models.PositiveIntegerField(default=3, verbose_name="Concurrent Sessions Limit"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="invoice_app.userrole",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Timestamp")),
                (
                    "event_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name="Event ID"),
                ),
                ("username", models.CharField(blank=True, max_length=150, verbose_name="Username")),
                ("session_key", models.CharField(blank=True, max_length=40, verbose_name="Session Key")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("ACCESS_DENIED", "Access Denied"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                            ("GENERATE_PDF", "Generate PDF"),
                            ("SEND_EMAIL", "Send Email"),
                            ("BACKUP", "Backup"),
                            ("RESTORE", "Restore"),
                            ("CONFIG_CHANGE", "Configuration Change"),
                            ("SECURITY_EVENT", "Security Event"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, db_index=True, max_length=100, verbose_name="Object Type"),
                ),
                ("object_id", models.CharField(blank=True, db_index=True, max_length=100, verbose_name="Object ID")),
                ("object_repr", models.CharField(blank=True, max_length=255, verbose_name="Object Representation")),
                ("description", models.TextField(verbose_name="Description")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Details")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name="IP Address"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="Request Method"),
                ),
                ("request_path", models.TextField(blank=True, null=True, verbose_name="Request Path")),
                (
                    "response_status",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Response Status"),
                ),
                ("old_values", models.JSONField(blank=True, default=dict, verbose_name="Old Values")),
                ("new_values", models.JSONField(blank=True, default=dict, verbose_name="New Values")),
                (
                    "is_compliance_relevant",
                    models.BooleanField(db_index=True, default=False, verbose_name="Compliance Relevant"),
                ),
                (
                    "is_security_event",
                    models.BooleanField(db_index=True, default=False, verbose_name="Security Event"),
                ),
                (
                    "retention_until",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Retention Until"),
                ),
                ("server_name", models.CharField(blank=True, max_length=255, verbose_name="Server Name")),
                (
                    "application_version",
                    models.CharField(blank=True, max_length=50, verbose_name="Application Version"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "permissions": [
                    ("view_audit_log", "Can view audit logs"),
                    ("export_audit_log", "Can export audit logs"),
                ],
                "indexes": [
                    models.Index(fields=["timestamp", "action"], name="invoice_app_timesta_6143b8_idx"),
                    models.Index(fields=["user", "timestamp"], name="invoice_app_user_id_f794da_idx"),
                    models.Index(fields=["object_type", "object_id"], name="invoice_app_object__365471_idx"),
                    models.Index(fields=["ip_address", "timestamp"], name="invoice_app_ip_addr_b6ef1f_idx"),
                    models.Index(
                        fields=["is_compliance_relevant", "timestamp"], name="invoice_app_is_comp_c55b52_idx"
                    ),
                    models.Index(fields=["is_security_event", "timestamp"], name="invoice_app_is_secu_29884f_idx"),
                    models.Index(fields=["severity", "timestamp"], name="invoice_app_severit_74c1bc_idx"),
                    models.Index(fields=["retention_until"], name="invoice_app_retenti_2c9e61_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CountryTaxRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("EXEMPT", "Exempt"),
                            ("REDUCED", "Reduced"),
                            ("STANDARD", "Standard"),
                            ("SUPER_REDUCED", "Super Reduced"),
                        ],
                        max_length=20,
                        verbose_name="Rate Type",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Tax Rate")),
                ("valid_from", models.DateField(verbose_name="Valid From")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="Valid To")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rates",
                        to="invoice_app.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country Tax Rate",
                "verbose_name_plural": "Country Tax Rates",
                "ordering": ["country__code", "-valid_from", "rate_type", "rate"],
                "indexes": [
                    models.Index(fields=["country", "valid_from", "valid_to"], name="invoice_app_country_02e9ee_idx"),
                    models.Index(fields=["country", "is_active"], name="invoice_app_country_cb1ec9_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "rate_type", "valid_from"), name="unique_country_rate_type_valid_from"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["invoice_number"], name="invoice_app_invoice_62afb6_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="invoice_app_status_ccfac9_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["issue_date"], name="invoice_app_issue_d_ec0ebd_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["company"], name="invoice_app_company_a514cf_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["product_code"], name="invoice_app_product_22cc78_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="invoice_app_name_4cc4d5_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "subcategory"], name="invoice_app_categor_11fc8b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active", "is_sellable"], name="invoice_app_is_acti_32a5f3_idx"),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(fields=["invoice", "product"], name="invoice_app_invoice_6d3ba0_idx"),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(fields=["product_code"], name="invoice_app_product_452778_idx"),
        ),
    ]
