# Generated by Django 5.1.15 on 2026-02-26 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0002_load_countries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_of_measure__in", [1, 2, 3, 4, 5, 6])),
                name="invoiceline_unit_of_measure_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_of_measure__in", [1, 2, 3, 4, 5, 6])), name="product_unit_of_measure_valid"
            ),
        ),
    ]
