# Generated by Django 5.1.15 on 2026-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0003_unit_of_measure_check_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="tax_category",
            field=models.CharField(
                blank=True,
                default="S",
                help_text="EN16931 tax category: S=Standard, Z=Zero, E=Exempt, AE=Reverse Charge, G=Export",
                max_length=5,
                verbose_name="Tax Category Code",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="tax_exemption_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Required for AE/G categories (e.g., 'Reverse Charge' or 'Export')",
                max_length=255,
                verbose_name="Tax Exemption Reason",
            ),
        ),
    ]
