# Generated by Django 5.1.15 on 2026-02-27 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0004_add_tax_category_to_invoiceline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="entry_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 Hash dieses Eintrags (inkl. Vorgänger-Hash)",
                max_length=64,
                verbose_name="Entry Hash",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_entry_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash des vorherigen Audit-Log-Eintrags (Kette)",
                max_length=64,
                verbose_name="Vorheriger Entry Hash",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Archiviert am"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cancelled_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancels_invoice",
                to="invoice_app.invoice",
                verbose_name="Storniert durch",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="content_hash",
            field=models.CharField(
                blank=True, help_text="SHA-256 Hash des Dokumentinhalts", max_length=64, verbose_name="Content Hash"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deletion_blocked",
            field=models.BooleanField(default=True, verbose_name="Löschung gesperrt"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="hash_algorithm",
            field=models.CharField(default="SHA256", max_length=20, verbose_name="Hash-Algorithmus"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Archiviert"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_locked",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Gesperrte Dokumente können nicht mehr geändert werden (GoBD)",
                verbose_name="Gesperrt",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="lock_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SENT", "Versendet"),
                    ("PAID", "Bezahlt"),
                    ("CANCELLED", "Storniert"),
                    ("MANUAL", "Manuell gesperrt"),
                ],
                max_length=50,
                verbose_name="Sperrgrund",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Gesperrt am"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gesperrt von",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="retention_until",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Mindestens 10 Jahre nach Erstellung (GoBD)",
                null=True,
                verbose_name="Aufbewahren bis",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["is_locked"], name="invoice_app_is_lock_f2d410_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["retention_until"], name="invoice_app_retenti_07341c_idx"),
        ),
    ]
