# Generated by Django 5.1.15 on 2026-03-09 11:53

import django.core.validators
import invoice_app.models.invoice_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0005_gobd_compliance"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("supporting_document", "Supporting Document"),
                    ("delivery_note", "Delivery Note"),
                    ("timesheet", "Timesheet"),
                    ("other", "Other"),
                ],
                default="supporting_document",
                max_length=30,
                verbose_name="Attachment Type",
            ),
        ),
        migrations.AddField(
            model_name="invoiceattachment",
            name="mime_type",
            field=models.CharField(
                blank=True,
                help_text="Detected MIME type of the uploaded file",
                max_length=100,
                verbose_name="MIME Type",
            ),
        ),
        migrations.AddField(
            model_name="invoiceattachment",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="Original filename as uploaded by the user",
                max_length=255,
                verbose_name="Original Filename",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceattachment",
            name="file",
            field=models.FileField(
                upload_to=invoice_app.models.invoice_models.attachment_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg", "csv", "xlsx"]
                    )
                ],
                verbose_name="File",
            ),
        ),
    ]
