# Generated by Django 5.1.15 on 2026-03-13 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0006_extend_invoice_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Verarbeitungstätigkeit")),
                ("purpose", models.TextField(verbose_name="Zweck der Verarbeitung")),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("contract", "Vertragserfüllung (Art. 6 Abs. 1 lit. b)"),
                            ("legal_obligation", "Rechtliche Verpflichtung (Art. 6 Abs. 1 lit. c)"),
                            ("legitimate_interest", "Berechtigtes Interesse (Art. 6 Abs. 1 lit. f)"),
                            ("consent", "Einwilligung (Art. 6 Abs. 1 lit. a)"),
                            ("public_interest", "Öffentliches Interesse (Art. 6 Abs. 1 lit. e)"),
                        ],
                        max_length=30,
                        verbose_name="Rechtsgrundlage",
                    ),
                ),
                ("legal_basis_detail", models.TextField(blank=True, verbose_name="Detaillierte Rechtsgrundlage")),
                ("data_subjects", models.TextField(verbose_name="Kategorien betroffener Personen")),
                ("data_categories", models.TextField(verbose_name="Kategorien personenbezogener Daten")),
                ("recipients", models.TextField(blank=True, verbose_name="Empfänger")),
                ("third_country_transfer", models.BooleanField(default=False, verbose_name="Drittlandübermittlung")),
                ("third_country_details", models.TextField(blank=True, verbose_name="Details Drittlandübermittlung")),
                ("retention_period", models.CharField(max_length=255, verbose_name="Löschfristen")),
                (
                    "tom_reference",
                    models.TextField(blank=True, verbose_name="Technische und organisatorische Maßnahmen"),
                ),
                (
                    "responsible_department",
                    models.CharField(blank=True, max_length=255, verbose_name="Verantwortliche Abteilung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
            ],
            options={
                "verbose_name": "Verarbeitungstätigkeit",
                "verbose_name_plural": "Verarbeitungsverzeichnis",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyImpactAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feature_name", models.CharField(max_length=255, verbose_name="Feature / System")),
                ("description", models.TextField(verbose_name="Beschreibung der Verarbeitung")),
                ("data_types", models.TextField(verbose_name="Betroffene Datentypen")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "Niedrig"), ("medium", "Mittel"), ("high", "Hoch"), ("critical", "Kritisch")],
                        max_length=10,
                        verbose_name="Risikoniveau",
                    ),
                ),
                ("risk_description", models.TextField(verbose_name="Risikobeschreibung")),
                ("mitigation_measures", models.TextField(verbose_name="Gegenmaßnahmen")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("in_review", "In Prüfung"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                            ("archived", "Archiviert"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("review_date", models.DateField(blank=True, null=True, verbose_name="Prüfdatum")),
                ("review_notes", models.TextField(blank=True, verbose_name="Prüfnotizen")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Prüfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datenschutz-Folgenabschätzung",
                "verbose_name_plural": "Datenschutz-Folgenabschätzungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("analytics", "Nutzungsanalyse"),
                            ("newsletter", "Newsletter"),
                            ("profiling", "Profiling"),
                            ("third_party", "Weitergabe an Dritte"),
                        ],
                        max_length=30,
                        verbose_name="Zweck",
                    ),
                ),
                ("granted", models.BooleanField(default=False, verbose_name="Einwilligung erteilt")),
                ("granted_at", models.DateTimeField(blank=True, null=True, verbose_name="Erteilt am")),
                ("revoked_at", models.DateTimeField(blank=True, null=True, verbose_name="Widerrufen am")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-Adresse")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einwilligungsnachweis",
                "verbose_name_plural": "Einwilligungsnachweise",
                "ordering": ["-granted_at"],
                "unique_together": {("user", "purpose")},
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "Auskunft (Art. 15)"),
                            ("erasure", "Löschung (Art. 17)"),
                            ("rectification", "Berichtigung (Art. 16)"),
                            ("portability", "Datenübertragbarkeit (Art. 20)"),
                            ("restriction", "Einschränkung (Art. 18)"),
                            ("objection", "Widerspruch (Art. 21)"),
                        ],
                        max_length=20,
                        verbose_name="Antragstyp",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Eingegangen"),
                            ("in_progress", "In Bearbeitung"),
                            ("completed", "Abgeschlossen"),
                            ("rejected", "Abgelehnt"),
                            ("escalated", "Eskaliert"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("subject_email", models.EmailField(max_length=254, verbose_name="E-Mail der betroffenen Person")),
                ("subject_name", models.CharField(max_length=255, verbose_name="Name der betroffenen Person")),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("user", "Benutzer"), ("partner", "Geschäftspartner")],
                        max_length=20,
                        verbose_name="Betroffenentyp",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("internal_notes", models.TextField(blank=True, verbose_name="Interne Notizen")),
                ("rejection_reason", models.TextField(blank=True, verbose_name="Ablehnungsgrund")),
                ("result_data", models.JSONField(blank=True, default=dict, verbose_name="Ergebnisdaten")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                ("deadline", models.DateField(verbose_name="Frist (30 Tage)")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Abgeschlossen am")),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dsr_processed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bearbeitet von",
                    ),
                ),
                (
                    "related_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dsr_requests",
                        to="invoice_app.businesspartner",
                        verbose_name="Verknüpfter Geschäftspartner",
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dsr_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verknüpfter Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Betroffenenanfrage (DSGVO)",
                "verbose_name_plural": "Betroffenenanfragen (DSGVO)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "deadline"], name="invoice_app_status_66e51d_idx"),
                    models.Index(fields=["subject_email"], name="invoice_app_subject_781ca4_idx"),
                ],
            },
        ),
    ]
