# Generated by Django 5.2.12 on 2026-04-14 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_gdpr_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, help_text='Fortlaufende Nummer für ausgehende Rechnungen (§ 14 UStG). NULL bei Eingangsrechnungen.', null=True, unique=True, verbose_name='Sequence Number'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sequence_number'], name='invoice_app_sequenc_386b2a_idx'),
        ),
        # Create PostgreSQL SEQUENCE for atomic invoice numbering.
        # Starts at 1; set_sequence_start management command adjusts this
        # at deployment time to continue from the customer's last number.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS invoice_sequence_number_seq START WITH 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS invoice_sequence_number_seq;",
        ),
        # Sync SEQUENCE with any existing sequence_number values in the table.
        # Only adjust if there are existing rows; otherwise keep default (1).
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM invoice_app_invoice
                        WHERE sequence_number IS NOT NULL
                    ) THEN
                        PERFORM setval('invoice_sequence_number_seq',
                            (SELECT MAX(sequence_number) FROM invoice_app_invoice),
                            true
                        );
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
