# Generated by Django 5.2.12 on 2026-04-15 13:21

import invoice_app.models.business_partner
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_add_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='leitweg_id',
            field=models.CharField(blank=True, help_text='Leitweg-ID for government invoices (XRechnung). Required when partner_type is GOVERNMENT.', max_length=46, validators=[invoice_app.models.business_partner.validate_leitweg_id], verbose_name='Leitweg-ID'),
        ),
    ]
