# Generated by Django 5.2.13 on 2026-04-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0009_add_leitweg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceattachment',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Invoice Attachment', 'verbose_name_plural': 'Invoice Attachments'},
        ),
    ]
