# Generated by Django 5.1 — manual copy of makemigrations output
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0010_alter_invoiceattachment_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="editing_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editing_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="In Bearbeitung von",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="editing_since",
            field=models.DateTimeField(blank=True, null=True, verbose_name="In Bearbeitung seit"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["editing_since"], name="invoice_app_editing_a925a1_idx"),
        ),
    ]
