# Generated by Django 5.2.14 on 2026-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0014_xrechnung_sent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract_reference',
            field=models.CharField(blank=True, help_text='Contract number or identifier (EN16931 BT-12)', max_length=200, verbose_name='Contract Reference'),
        ),
    ]
