# Generated by Django 5.2.14 on 2026-05-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0015_add_contract_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Invoice contact person name (EN16931 BT-39)', max_length=100, verbose_name='Contact Name'),
        ),
    ]
