# Generated by Django 5.2.14 on 2026-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0016_add_company_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_period_end',
            field=models.DateField(blank=True, help_text='End of billing/service period (EN16931 BT-74)', null=True, verbose_name='Billing Period End'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateField(blank=True, help_text='Start of billing/service period (EN16931 BT-73)', null=True, verbose_name='Billing Period Start'),
        ),
    ]
