# Generated by Django 5.2.14 on 2026-05-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0019_invoice_delivery_address_bt77_bt80_prepaid_rounding'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='discount_reason_code',
            field=models.CharField(blank=True, default='', help_text='UNTDID 5189 or 7161 reason code for line-level allowance/charge (EN16931 BT-140/BT-145)', max_length=10, verbose_name='Discount Reason Code'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_exemption_reason_code',
            field=models.CharField(blank=True, default='', help_text="VATEX code for VAT exemption reason (EN16931 BT-121, e.g. 'VATEX-EU-AE')", max_length=20, verbose_name='VAT Exemption Reason Code'),
        ),
    ]
