# Generated by Django 5.2.14 on 2026-05-15 11:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0020_invoiceline_reason_codes_bt121_bt140_bt145'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='gross_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Price before price-level discount (EN16931 BT-148). Net price = gross_price - price_discount.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gross Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, default='', help_text='Global Trade Item Number, 13 or 14 digits (EN16931 BT-156/BT-157)', max_length=14, verbose_name='GTIN / EAN'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_item_id',
            field=models.CharField(blank=True, default='', help_text="Seller's own item identifier (EN16931 BT-155), e.g. catalog number", max_length=50, verbose_name='Seller Item ID'),
        ),
    ]
