# Generated by Django 6.0.7 on 2026-07-30 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0021_invoiceline_gross_price_product_seller_id_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_representative_address_line1',
            field=models.CharField(blank=True, help_text="Street of the seller's tax representative (EN16931 BT-64)", max_length=255, verbose_name='Tax Representative Address Line 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_representative_city',
            field=models.CharField(blank=True, help_text="City of the seller's tax representative (EN16931 BT-66)", max_length=100, verbose_name='Tax Representative City'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_representative_country',
            field=models.CharField(blank=True, help_text="Country of the seller's tax representative (EN16931 BT-69)", max_length=100, verbose_name='Tax Representative Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_representative_name',
            field=models.CharField(blank=True, help_text="Name of the seller's tax representative (EN16931 BT-62)", max_length=255, verbose_name='Tax Representative Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_representative_postal_code',
            field=models.CharField(blank=True, help_text="Postal code of the seller's tax representative (EN16931 BT-67)", max_length=20, verbose_name='Tax Representative Postal Code'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_representative_vat_id',
            field=models.CharField(blank=True, help_text="VAT ID of the seller's tax representative (EN16931 BT-63)", max_length=50, verbose_name='Tax Representative VAT ID'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payee_id',
            field=models.CharField(blank=True, help_text='Payee identifier, e.g. bank/factoring reference (EN16931 BT-60)', max_length=100, verbose_name='Payee Identifier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payee_name',
            field=models.CharField(blank=True, help_text='Name of the payee if different from the seller (EN16931 BT-59)', max_length=200, verbose_name='Payee Name'),
        ),
        migrations.CreateModel(
            name='InvoiceLineAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='EN16931 BT-160', max_length=100, verbose_name='Attribute Name')),
                ('value', models.CharField(help_text='EN16931 BT-161', max_length=200, verbose_name='Attribute Value')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort Order')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='invoice_app.invoiceline', verbose_name='Invoice Line')),
            ],
            options={
                'verbose_name': 'Invoice Line Attribute',
                'verbose_name_plural': 'Invoice Line Attributes',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
