"""
Django settings for invoice_project project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os  # noqa: I001
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from a .env file
load_dotenv()


def get_secret(env_name, default=None):
    """Read a config value from Docker Secrets, falling back to env vars.

    Docker Secrets are files in /run/secrets/ (mounted by Docker Swarm or
    Compose ``secrets:`` stanza).  The file name must match the lower-cased
    env var name, e.g. ``DJANGO_SECRET_KEY`` → ``/run/secrets/django_secret_key``.
    """
    secret_path = Path("/run/secrets") / env_name.lower()
    if secret_path.is_file():
        return secret_path.read_text().strip()
    return os.getenv(env_name, default)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("The DJANGO_SECRET_KEY environment variable is not set.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")

# Django 6.0 Compatibility: HTTPS Scheme Preparation (Issue #9)
# Set to True to opt into HTTPS as default scheme (recommended for production)
# Set to False to maintain HTTP default (development/testing)
IS_PRODUCTION = os.getenv("DJANGO_ENV", "development") == "production"
FORMS_URLFIELD_ASSUME_HTTPS = IS_PRODUCTION

# HTTPS Security Settings (Phase 1 - Security Implementation)
# Only active when DJANGO_ENV=production is set
# See: docs/SECURITY_IMPLEMENTATION.md Phase 1.1
if IS_PRODUCTION:
    # SSL/HTTPS Configuration
    SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS
    SECURE_REDIRECT_EXEMPT = [
        r"^metrics$",  # Prometheus scraping (internal, no HTTPS needed)
        r"^health/$",  # Health checks (Kubernetes probes)
    ]
    SESSION_COOKIE_SECURE = True  # Cookies only over HTTPS
    CSRF_COOKIE_SECURE = True  # CSRF tokens only over HTTPS

    # Recognize HTTPS from proxy/load balancer
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Security Headers (always active, regardless of environment)
X_FRAME_OPTIONS = "DENY"  # Prevent clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
# SECURE_BROWSER_XSS_FILTER removed — deprecated since Django 4.1, no effect in modern browsers
SECURE_REFERRER_POLICY = "same-origin"  # Limit referrer information


# Application definition

INSTALLED_APPS = [
    "django_prometheus",  # Must be first to instrument DB & cache early
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "invoice_app.apps.InvoiceAppConfig",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    "drf_spectacular",
    "django_extensions",
]

# Auth redirect URLs (django.contrib.auth session login)
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Pagination - required for frontend to work correctly
    "DEFAULT_PAGINATION_CLASS": "invoice_app.api.pagination.FlexiblePageNumberPagination",
    "PAGE_SIZE": 10,
    # drf-spectacular schema generation
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Global exception handler for consistent error responses
    "EXCEPTION_HANDLER": "invoice_app.api.exception_handlers.global_exception_handler",
}

# drf-spectacular settings (OpenAPI 3.0)
SPECTACULAR_SETTINGS = {
    "TITLE": "eRechnung API",
    "DESCRIPTION": (
        "REST API for eRechnung Django App - Electronic Invoice Management "
        "(ZUGFeRD/Factur-X compliant).\n\n"
        "**Single Source of Truth**: This openapi.json is the authoritative API contract. "
        "Fields not listed here do not exist in the public API."
    ),
    "VERSION": "v1",
    "CONTACT": {"name": "eRechnung Support"},
    "LICENSE": {"name": "MIT"},
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/",
    "COMPONENT_SPLIT_REQUEST": True,
    "ENUM_NAME_OVERRIDES": {
        "InvoiceStatusEnum": "invoice_app.models.InvoiceStatus",
        "GdprRequestStatusEnum": "invoice_app.models.RequestStatus",
        "DpiaAssessmentStatusEnum": "invoice_app.models.AssessmentStatus",
    },
    "SECURITY": [
        {"Bearer": []},
    ],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "Bearer": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": 'JWT authorization. Example: "Authorization: Bearer {token}"',
            },
            "Basic": {
                "type": "http",
                "scheme": "basic",
            },
        },
    },
}

# CORS is handled by API-Gateway in production (like K8s Ingress)
# Only enable Django CORS middleware when running without gateway
BEHIND_GATEWAY = os.environ.get("BEHIND_GATEWAY", "true").lower() == "true"

MIDDLEWARE = [
    # Prometheus: request timing must wrap all other middleware (first in, last out)
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    # Correlation ID: assign early so all downstream logs carry the request_id
    "invoice_project.middleware.RequestIDMiddleware",
    # Health check SSL exemption (must be early!)
    "invoice_project.middleware.HealthCheckSSLExemptMiddleware",
    # Conditionally enable CORS middleware for E2E tests and local dev
    *(["corsheaders.middleware.CorsMiddleware"] if not BEHIND_GATEWAY else []),
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Prometheus: capture response status after all processing
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "invoice_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "invoice_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Check if running in Docker
IS_DOCKER = os.getenv("IS_DOCKER", "false").lower() == "true"

# Prefer POSTGRES_* variables, but fall back to DB_* if not set
db_name = get_secret("POSTGRES_DB", os.getenv("DB_NAME"))
db_user = get_secret("POSTGRES_USER", os.getenv("DB_USER"))
db_password = get_secret("POSTGRES_PASSWORD", os.getenv("DB_PASSWORD"))
db_host = os.getenv("POSTGRES_HOST", os.getenv("DB_HOST", "db")) if IS_DOCKER else "localhost"
db_port = os.getenv("POSTGRES_PORT", os.getenv("DB_PORT", "5432"))

# Raise an error if required database settings are missing
if not all([db_name, db_user, db_password]):
    missing = []
    if not db_name:
        missing.append("POSTGRES_DB/DB_NAME")
    if not db_user:
        missing.append("POSTGRES_USER/DB_USER")
    if not db_password:
        missing.append("POSTGRES_PASSWORD/DB_PASSWORD")
    raise ValueError(f"Missing required database settings: {', '.join(missing)}")

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": db_name,
        "USER": db_user,
        "PASSWORD": db_password,
        "HOST": db_host,
        "PORT": db_port,
    },
}

# PostgreSQL SSL configuration
# Set DATABASE_SSL_MODE to control SSL behavior:
#   "disable"  - no SSL (not recommended for production)
#   "prefer"   - use SSL if available (default for backwards compatibility)
#   "require"  - require SSL, no CA verification
#   "verify-ca" - require SSL + verify server cert against CA
#   "verify-full" - require SSL + verify server cert + hostname
_db_ssl_mode = os.getenv("DATABASE_SSL_MODE", "prefer")
if _db_ssl_mode != "disable":
    DATABASES["default"].setdefault("OPTIONS", {})["sslmode"] = _db_ssl_mode
    _db_ssl_ca = os.getenv("DATABASE_SSL_CA", "")
    if _db_ssl_ca:
        DATABASES["default"]["OPTIONS"]["sslrootcert"] = _db_ssl_ca


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
# Use container-internal directory - no volume mount needed
STATIC_ROOT = os.getenv("STATIC_ROOT", os.path.join(BASE_DIR, "static"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# PDF and File Storage Settings
MEDIA_URL = "/media/"
# Use container-internal directory - no volume mount needed
MEDIA_ROOT = os.getenv("MEDIA_ROOT", os.path.join(BASE_DIR, "media"))

# PDF Generation settings
GHOSTSCRIPT_PATH = "/usr/bin/gs"  # Path to Ghostscript executable
# sRGB ICC profile embedded as RGB OutputIntent in PDF/A-3 (required by ISO 19005-3 §6.2.4.3
# when DeviceRGB colour spaces are used). Ghostscript ships this profile on Debian/Ubuntu.
PDFA_RGB_ICC_PROFILE = "/usr/share/color/icc/ghostscript/srgb.icc"
PDF_OUTPUT_DIR = os.path.join(MEDIA_ROOT, "invoices")
XML_OUTPUT_DIR = os.path.join(MEDIA_ROOT, "xml")

# Async PDF generation via Celery (Issue #4). Set to True to offload PDF/A-3
# generation to a background worker instead of blocking the request cycle.
ENABLE_ASYNC_PDF = os.getenv("ENABLE_ASYNC_PDF", "False").lower() == "true"

# Invoice Edit Lock — Pessimistic application-level locking for concurrent edits.
# Locks expire automatically after this many minutes (protects against abandoned sessions).
INVOICE_EDIT_LOCK_TIMEOUT_MINUTES = int(os.getenv("INVOICE_EDIT_LOCK_TIMEOUT_MINUTES", "30"))

# Note: Directories are created by init script, not during settings import

# XML Validation Settings
# Schematron validation via Saxon-HE (saxonche) for EN16931 XPath 2.0+ rules
# Set ENABLE_SCHEMATRON_VALIDATION=False to disable (e.g. for faster tests)
ENABLE_SCHEMATRON_VALIDATION = os.getenv("ENABLE_SCHEMATRON_VALIDATION", "True").lower() == "true"
SCHEMATRON_STRICT_MODE = os.getenv("SCHEMATRON_STRICT_MODE", "False").lower() == "true"
XML_VALIDATION_TIMING_THRESHOLD_MS = int(os.getenv("XML_VALIDATION_TIMING_THRESHOLD_MS", "200"))

# Test runner — cleans up leftover XML artifacts before each test run
TEST_RUNNER = "invoice_project.test_runner.ERehnungTestRunner"

# Celery settings
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Celery broker URL
CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/0"

# Celery beat schedule — periodic tasks
CELERY_BEAT_SCHEDULE = {
    "collect-business-metrics": {
        "task": "monitoring.collect_business_metrics",
        "schedule": 60.0,  # every 60 seconds
    },
}


# JWT Authentication Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": "eRechnung-Django-App",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=7),
}

# CORS Configuration
# NOTE: CORS is handled by API-Gateway (nginx) in production
# These settings are kept as fallback for direct Django access (e.g., tests)
# When BEHIND_GATEWAY=true, CorsMiddleware is disabled
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://localhost:5173",
    "http://127.0.0.1:5173",
    "https://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ---------------------------------------------------------------------------
# Logging — structured JSON output with correlation IDs
# LOG_LEVEL=CRITICAL suppresses logs during tests:
#   LOG_LEVEL=CRITICAL docker compose exec web python project_root/manage.py test
# ---------------------------------------------------------------------------
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOG_DIR = os.getenv("LOG_DIR", os.path.join(BASE_DIR, "..", "logs"))
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "invoice_project.logging.RequestIDFilter",
        },
    },
    "formatters": {
        "json": {
            "()": "invoice_project.logging.ERehnungJsonFormatter",
        },
        "simple": {
            "format": "%(asctime)s [%(levelname)s] %(message)s",
        },
    },
    "handlers": {
        "console_json": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["request_id"],
        },
        "console_simple": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file_json": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "erechnung.log"),
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,
            "formatter": "json",
            "filters": ["request_id"],
            "encoding": "utf-8",
            "delay": True,
        },
    },
    "loggers": {
        # Application loggers → JSON to file (no more stdout)
        "invoice_app": {
            "handlers": ["file_json"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "invoice_project": {
            "handlers": ["file_json"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        # Django framework
        "django": {
            "handlers": ["file_json"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["file_json"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.server": {
            "handlers": ["file_json"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        # Celery
        "celery": {
            "handlers": ["file_json"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        # Third-party libraries that produce excessive DEBUG/INFO noise
        "fontTools": {"level": "WARNING", "handlers": ["console_simple"], "propagate": False},
        "fonttools": {"level": "WARNING", "handlers": ["console_simple"], "propagate": False},
        "facturx": {"level": "WARNING", "handlers": ["console_simple"], "propagate": False},
        "weasyprint": {"level": "WARNING", "handlers": ["console_simple"], "propagate": False},
        "PIL": {"level": "WARNING", "handlers": ["console_simple"], "propagate": False},
    },
    "root": {
        "handlers": ["file_json"],
        "level": "INFO",
    },
}
