# Remove postgres CA cert volume/mount from celery-worker in staging
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  template:
    spec:
      containers:
      - name: celery-worker
        volumeMounts:
        - mountPath: /etc/ssl/postgres
          $patch: delete
      volumes:
      - name: postgres-ca
        $patch: delete
