# Generated by Django 5.1 on 2025-07-04 10:53

from django.db import migrations


def create_default_organization(apps, schema_editor):
    """
    Create a default organization to be used for migrations and as fallback.
    """
    Organization = apps.get_model("invoice_app", "Organization")

    # Check if any organization already exists
    if Organization.objects.count() == 0:
        Organization.objects.create(
            name="Default Organization",
            address_line1="Default Address",
            postal_code="00000",
            city="Default City",
            country="Default Country",
        )


def reverse_default_organization(apps, schema_editor):
    """
    Remove the default organization if it exists.
    """
    Organization = apps.get_model("invoice_app", "Organization")
    Organization.objects.filter(name="Default Organization").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_organization, reverse_default_organization),
    ]
