# Generated by Django 5.1 on 2025-07-04 10:54

from django.db import migrations, models
import django.db.models.deletion


def get_default_org_id(apps, schema_editor):
    """
    Get the ID of the default organization, or the first one found.
    """
    organization_model = apps.get_model("invoice_app", "Organization")

    # Try to get the default organization first
    default_org = organization_model.objects.filter(name="Default Organization").first()

    # If no default organization exists, just get the first one
    if not default_org:
        default_org = organization_model.objects.first()

    # If still no organization exists, return None (should not happen due to previous migration)
    return default_org.id if default_org else None


def set_default_values(apps, schema_editor):
    """
    Set default values for all invoices that have NULL supplier or customer.
    """
    invoice_model = apps.get_model("invoice_app", "Invoice")

    default_org_id = get_default_org_id(apps, schema_editor)

    if default_org_id:
        # Update all invoices that have NULL supplier
        invoice_model.objects.filter(supplier__isnull=True).update(supplier_id=default_org_id)

        # Update all invoices that have NULL customer
        invoice_model.objects.filter(customer__isnull=True).update(customer_id=default_org_id)


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0002_create_default_organization"),
    ]

    operations = [
        # First, make the foreign key fields nullable temporarily
        migrations.AlterField(
            model_name="invoice",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_invoices",
                to="invoice_app.organization",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_invoices",
                to="invoice_app.organization",
                verbose_name="Customer",
            ),
        ),
        # Run the function to set default values
        migrations.RunPython(set_default_values, migrations.RunPython.noop),
        # Make the fields non-nullable again
        migrations.AlterField(
            model_name="invoice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_invoices",
                to="invoice_app.organization",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_invoices",
                to="invoice_app.organization",
                verbose_name="Customer",
            ),
        ),
    ]
