---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
spec:
  encryptedData:
    smtp_password: AgCrYSNo7JaUrq60MvKHyt9hMLpbbm7ynr7NjtqWFXgdrTATT2lyXQCrR6bK20ptBXD+5c+Sfc3LRPlJ+jZ/X2QoW91DVnydzrmYKPlCSF7OWaAJczTG/ssuYYxlyIQogSwTIgA1+HmblXafCY6cawAfRkumKwveoHxCcxbQ4+e49YpGTFN2OLbAcCooX55Zn0OjGDGzHR2gsiwASaRqfcCoQZv+LeEnb/NLZuuc9lzUVxwVGIGA4NuMNDGZgRqZ29VQSEaKazyRv2eKm9UKYSEdmeFn5Eg1zTj8S3Y1/iZ2jmP9NOeB5/GBb7Y/U7dO1z3mW0WNtGHMu21cPD93Ft60NTMyUpC5HttXZGu9FfN1pqM2SIf2iF3f0D6jYttlftMtSLysXX+AOSMKMzU9MOQRyr7sqmYNfzGAr1QHbhXdOl/mh2M5oAy2DBIY724mavgErIdm+0V2Bw+E52zcqgmLJ/kBgkaqa68vdZ/bcIUcxlPnIAf9Y0Z3VkWIcP+/GNlCjokpONouQqRiOjgDP3hgzKIIwq0FqqZRrdTZiHgET/3glFV1SE1EwTB6DqFKBM1WZQYFX/ulWpu4jUKvdkL8DFbPuMLufer3vVNJkpx5GCSycCELuIaHRmbewvSViovreP7PBK02i02KerkZAfR9y/fgadaBQmlZ0JA8WiqkyUHA5NugIjGZ5WYX1+Hwrblgjjn72TGvEaR0ZjrzyQSy2I2p
  template:
    metadata:
      name: alertmanager-smtp
      namespace: monitoring
